### ISSUE TITLE
"InvalidOperationException: Collection was modified" when executing ObjectPool.Remove

### ISSUE THREAD

**Issue by Armo-03** [LemonUIbyLemon/LemonUI#44]
So I'm trying to remove a list of submenus to replace them with new ones and I'm getting this error. Sometimes also happens after adding submenus.

**Comment by justalemon** [comment]
Sadly, I need the exception traceback to know why it happens.

Feel free to post the exception traceback once you have it.

**Comment by justalemon** [comment]
I'm closing this issue as no traceback was provided. Feel free to post the traceback and Ill reopen the issue.

**Comment by KimTisott** [comment]
@justalemon 

[19:17:35] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[19:17:35] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[19:17:35] [DEBUG] Loading scripts from C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts ...
[19:17:35] [DEBUG] Loading assembly LemonUI.SHVDN3.dll ...
[19:17:35] [INFO] Found 0 script(s) in LemonUI.SHVDN3.dll.
[19:17:35] [DEBUG] Loading assembly Meta.dll ...
[19:17:35] [INFO] Found 1 script(s) in Meta.dll resolved to API 3.4.0.
[19:17:35] [DEBUG] Instantiating script Main ...
[19:17:38] [INFO] Started script Main.
[19:17:41] [ERROR] Caught fatal unhandled exception:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at LemonUI.ObjectPool.Process()
   at Main.OnTick(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[19:17:41] [ERROR] The exception was thrown while executing the script Main.
[19:17:41] [WARNING] Aborted script Main.

The exception happens when adding an item to the ObjectPool in a different thread, such as when adding items to hooked events, like the Opening event handler por example.

The way I see it, you should implement a manual concurrency with locks, or replace the objects data type by a thread safe structure, e.g. ConcurrentDictionary.

`private readonly List<IProcessable> objects = new List<IProcessable>();`

to

`private readonly ConcurrentDictionary<IProcessable> objects = new();`

https://docs.microsoft.com/pt-br/dotnet/standard/collections/thread-safe/

**Comment by justalemon** [comment]
> The exception happens when adding an item to the ObjectPool in a different thread, such as when adding items to hooked events, like the Opening event handler por example.

In my defense, you should only be operating LemonUI and other libraries that interact with the game in the game's thread provided by SHVDN.

**Comment by KimTisott** [comment]
I understand the limitations behind this, but don't you think it's weird that you can't use the NativeMenu events to manage objects in the provided ObjectPool, as they're all from the same API? 

I can submit a pull request with the changes if you're willing to accept them.
