### ISSUE TITLE
Big Message weapon purchased crash

### ISSUE THREAD

**Issue by I-E-A-I-A-I-O** [LemonUIbyLemon/LemonUI#54]
I get this error when trying to use the Big Message scaleform:

> System.ArgumentException: Unexpected argument type UInt32.
Parameter name: parameters
   at LemonUI.Scaleform.BaseScaleform.CallFunctionBase(String function, Object[] parameters)
   at LemonUI.Scaleform.BaseScaleform.CallFunction(String function, Object[] parameters)
   at LemonUI.Scaleform.BigMessage..ctor(String title, String weapon, WeaponHash hash)

It happens when this line gets executed:

![https://i.imgur.com/2J0yTYd.png](https://i.imgur.com/2J0yTYd.png)

**Comment by justalemon** [comment]
This happens because we don't have an entry for unsigned integers in CallFunctionBase. This affects all scaleforms that pass unsigned integers for them to work.

https://github.com/justalemon/LemonUI/blob/7132abddf5ea76266d3bdb84f048e285b784f46c/LemonUI/Scaleform/BaseScaleform.cs#L109-L181
